### ISSUE TITLE
iPhone 12 Pro Max IOS16.6.1 Not working

### ISSUE THREAD

**Issue by YGQ8988** [straight-tamago/misaka#102]
KFD Mode Please try kopen

**Comment by Zhpf1103** [comment]
the same as me on 12pm 16.6

**Comment by raisons** [comment]
grayed 'tips' button

**Comment by gobulee** [comment]
12PM 16.61 grayed 'tips' button

**Comment by YGQ8988** [comment]
> the same as me on 12pm 16.6

I can use the latest version of PureKFD。You can give it a try，good luck！

**Comment by YGQ8988** [comment]
> 12PM 16.61 grayed 'tips' button

I can use the latest version of PureKFD。You can give it a try，good luck！

**Comment by YGQ8988** [comment]
> grayed 'tips' button

I can use the latest version of PureKFD。You can give it a try，good luck！
