### ISSUE TITLE
iPhone 11 Pro 16.6 - Got "Done - OK" , BUT ... 

### ISSUE THREAD

**Issue by sb88gc** [straight-tamago/misaka#139]
after choosing "Tips" for TrollStore Help, It says "Done, OK", but automatically resprings or not,
It JUST WOULD NOT show TrollStore

(Changes are NOT committed or retained ??)

**Comment by jejer** [comment]
Please try:
1. use misaka to respring.
2. after respring, start Tips to install trollstore.
