### ISSUE TITLE
[iOS 16.4.1 iP14] A error occurred when clicking to install `TrollStore`

### ISSUE THREAD

**Issue by PoetryU** [straight-tamago/misaka#14]
Error when clicking "Tips", displaying `error 2`

I guess it was caused by the offset without adapting to the KFD vulnerability.

**Comment by luisruizlatic** [comment]
Hey I finally made it, I don't know how but this is what I did:

1- I used the following process on the "Books App" (var/containers/bundle/application/com.apple.iBook where I replaced the Books file with the persistent installer downloaded from the trollstore github: https://github.com/opa334/TrollStore/releases):

![image_2023-11-28_114505982](https://github.com/straight-tamago/misaka/assets/49820450/4c006dbd-64bf-4185-a0a9-8fcc2ed5fff1)

2- After restart it didn't work so I went back to Misaka and used the "Install Trollstore" button and selected "Books" app again. after the respring it worked this time and installed trollstore from books

**Comment by chenzgsir** [comment]
The iBook app works fine.My device is an iPhone 12 Pro - 16.3.1.I simply covered it with misaka and restarted it. Thank you very much.

**Comment by PoetryU** [comment]
Trollstorehelper returned error 1
