### ISSUE TITLE
iPhone 12 iOS16.5.1(20F75) no work and crash，KFD Mode Please try kopen

### ISSUE THREAD

**Issue by swordman20** [straight-tamago/misaka#140]
![IMG_2266](https://github.com/straight-tamago/misaka/assets/7270004/86d1da54-36de-449c-b93b-4210deb89dd6)
fail

**Comment by swordman20** [comment]
On misaka v8.0.7 beta

**Comment by chenchong22** [comment]
the same!

**Comment by swordman20** [comment]
<img width="1233" alt="image" src="https://github.com/straight-tamago/misaka/assets/7270004/7ec5fa76-d3b4-46de-ac72-e4c935d56dbf">
On misaka v8.0.8, it was resolved. Thank you, misaka
