### ISSUE TITLE
iPad8,3 16.6 app crash or kernel panic

### ISSUE THREAD

**Issue by KernelFox0** [straight-tamago/misaka#159]
When I try to kopen (puaf_landa) one of these thing happen:
- App crashes but doesn’t close, restarting itself
- App fully crashes
- Kernel panic
- Screen flashes pink then kernel panic

One time I only got a springboard restart. And once after a kernel panic misaka got deleted from my iPad.

**Comment by HH7H** [comment]
Same thing on iPad14,3

**Comment by Eric120110** [comment]
Same on iPad8,11

**Comment by cyonixx** [comment]
same on iPad13,19 iOS 16.4.1

**Comment by KernelFox0** [comment]
Just tested it. 8.0.9 has the same problem.

**Comment by KernelFox0** [comment]
And 8.1.1 is still not working
