### ISSUE TITLE
You suck at developing.

### ISSUE THREAD

**Issue by someguy192** [straight-tamago/misaka#194]
And before you say "yOu cAnnOt coDE soMeThING wIkE tHiS" No, I cannot. But if you're gonna advertise this as working, then it doesnt work for a ton of people (as seen by a billion issues here), then you're false advertising. Wake up and actually fix this, don't be sending out half assed updates that are "KFD fix" it excites everyone, but when their device crashes again, they get disappointed because of YOU!

**Comment by vgg102** [comment]
Put up or shut up.

**Comment by roeegh** [comment]
skill issue tbh just get good
