### ISSUE TITLE
iPad Pro 2018 (A12X) iPadOS16.5 still not working

### ISSUE THREAD

**Issue by KuaiCode** [straight-tamago/misaka#198]
Misaka version : 8.1.1
Device : iPad Pro 2018 (A12X A1980 iPad8,1)
iPadOS version : 16.5(20F66)

Clicking "ok" on the kopen popup window exits Misaka.

**Comment by arlitlodest** [comment]
so do i

**Comment by arlitlodest** [comment]
> so do i 我也是

 try more  successfully！

**Comment by KuaiCode** [comment]
Did you succeed after many attempts?

**Comment by KuaiCode** [comment]
Hey guys, if you have the same device, system as me, please do try more, I just used Misaka 8.1.1 and it already worked!

**Comment by arlitlodest** [comment]
> Hey guys, if you have the same device, system as me, please do try more, I just used Misaka 8.1.1 and it already worked!

right，its worked
