### ISSUE TITLE
NO TROLLSTORE from Misaka 8.1.1 - iOS 16.6 on iPhone 11 Pro

### ISSUE THREAD

**Issue by sb88gc** [straight-tamago/misaka#217]
All 3 Steps seem to have passed

1.   ToolBox --> Install TrollStore  [✔]

2.   TrollStore Installer                   [✔]

3.   Tips                                           [✔]

Pop-up dialog showed                   [Done]

YET,  NOTHING NEW added to device

**Comment by fenfenS** [comment]
force to power off immediately since the pop-up dialog showed, power on after several minutes.
