### ISSUE TITLE
Tweaks are Not Applying & Phone Restarts

### ISSUE THREAD

**Issue by UserPendslol** [straight-tamago/misaka#230]
V 8.1.1 w/ Trollstore
iPhone 13
iOS 16.6

Settings: frontboard, Landa, kfd, kclose, no running in the background (already tried that), no dev mode (attempted)

Nothing changes when I have the checks mark enabled, restart, or respringing my phone (with another app).
The Phone Restarts occasionally when misaka is opened.

I am also using tweaks from pure kfd

**Comment by VIPMyStyle** [comment]
把其他的全部卸载掉，在重启设备，重新全新安装misaka8.1.1

**Comment by UserPendslol** [comment]
The phone still restarts randomly, but si figured out how to get some tweaks to work
