### ISSUE TITLE
Always crashes when trying kopen

### ISSUE THREAD

**Issue by SoNiCtHeDgE** [straight-tamago/misaka#245]
misaka 8.2.0
iPad Pro 11-inch 3rd gen
M1 processor
iPadOS 16.6.1

**Comment by HH7H** [comment]
Try purekfd

**Comment by SoNiCtHeDgE** [comment]
> Try purekfd

I did but it didn't work either.

btw I tried the latest misaka 8.2.1 and it worked pretty well.
Salute to the developers!

**Comment by Techdrips** [comment]
How did you get the new version? Plz help me get this to work
