### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kaisyaliu** [straight-tamago/misaka#8]
installing trollstore error returned 1

**Comment by kaisyaliu** [comment]
ios 16.3.1 and iphone 14 pro

**Comment by PoetryU** [comment]
iOS16.3.1 ip14
the same problem

Error when clicking "tips", displaying `error 2`

**Comment by yanyu2023** [comment]
> iOS16.4.1 ip14 the same problem
> 
> Error when clicking "tips", displaying `error 2`

me too

**Comment by kaisyaliu** [comment]
fixed, installed success!

**Comment by luisruizlatic** [comment]
> fixed, installed success!

How did you fix it? I'm using 16.1.1

**Comment by PoetryU** [comment]
> > installing trollstore error returned 1
> 
> iphone 13 pro,same problem How did you fix it? I tried many times.

https://mp.weixin.qq.com/s/Ar09UYqduss9ehwAruElww
https://mp.weixin.qq.com/s/AT6E0ojcCJ2HHWjpicOdYg

**Comment by NanOns** [comment]
> > > installing trollstore error returned 1
> > 
> > 
> > iphone 13 pro,same problem How did you fix it? I tried many times.
> 
> https://mp.weixin.qq.com/s/Ar09UYqduss9ehwAruElww https://mp.weixin.qq.com/s/AT6E0ojcCJ2HHWjpicOdYg

文件替换那个 走不通,照不到

**Comment by Cenglou829** [comment]
I have solved this problem and can solve it by following the video method
https://www.bilibili.com/video/BV1kH4y1y74u?vd_source=23ed5fd686dc1b896c39877e1f7fd6cf

**Comment by Cenglou829** [comment]
> iOS16.4.1 ip14

click respring and try again
